### ISSUE TITLE
quit behavior

### ISSUE THREAD

**Issue by nodelman** [jessealama/ce-el#2]
When making interactive corrections, it would be good if "quit" would leave you where you are in the file so that you can make other changes in that area.  Alternatively, an additional "pause" option could be used instead.

**Comment by peoppenheimer** [comment]
The ability to open an embedded level of editing is indeed desirable.  Several existing emacs commands offer this, under the name "recursive" edit.  (One of the missing features of the existing command-line-level ce tools is that they do not offer this.)

**Comment by jessealama** [comment]
The quit functionality that Uri referred to nearly a year ago had to do with the Emacs-based quote-fixer-upper.  That one works as you might expect.  It's not strictly speaking Emacs's "recursive edit", but close enough.

Note that recursive editing is somewhat deprecated by the ELisp community.  From the Emacs manual:

```
    In general, we try to minimize the use of recursive editing levels in GNU Emacs. This is because they constrain you to “go back” in a particular order--from the innermost level toward the top level. When possible, we present different activities in separate buffers so that you can switch between them as you please. Some commands switch to a new major mode which provides a command to switch back. These approaches give you more flexibility to go back to unfinished tasks in the order you choose.
```

And, in the ELisp manual:

```
    Most applications should not use recursive editing, except as part of using the minibuffer. Usually it is more convenient for the user if you change the major mode of the current buffer temporarily to a special major mode, which should have a command to go back to the previous mode. (The ‘e’ command in Rmail uses this technique.) Or, if you wish to give the user different text to edit “recursively,” create and select a new buffer in a special mode. In this mode, define a command to complete the processing and go back to the previous buffer. (The ‘m’ command in Rmail does this.)
```

This approach is taken in the latest ce-dash code.  It supports a delimited "recursive edit" by allowing one to edit, at most, a single character data section of the XML parse tree, rather than the entire document (which is what undelimited, arbitrary recursive edit permits).

**Comment by jessealama** [comment]
I'm closing this issue.  I fixed this a long time ago.  I could go back and find the precise commit that did this and edit its commit message so that the GitHub issues automaton would close the issue itself, but that would require a git rebase of hundreds of commits.

**Comment by peoppenheimer** [comment]
Jesse,

Thanks for explaining thoroughly!  What you have actually done, in accordance with community best practice, is clearly superior to the unrestricted "recursive edit" that I had in mind.

Paul

peoppenheimer.org
